spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5433/t1_demo"
    username: "postgres"
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: t1-demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

security:
  token: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  expiration: 86400000

client:
  service:
    url: http://localhost:8081

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    topic:
      account_registration: t1_demo_accounts
      transactions_registration: t1_demo_transactions
      metrics: t1_demo_metrics
      transactions_result: t1_demo_transaction_result
      transactions_accept: t1_demo_transaction_accept
    consumer:
      properties:
        session.timeout.ms: 150000
        max.partition.fetch.bytes: 300000
        max.poll.records: 1
        max.poll.interval.ms: 3000
  client:
    service:
      url: http://localhost:8081
  metrics:
    enabled: true
    database:
      enabled: true
  time:
    threshold: 10000
    fixed_rate: 60000

transaction:
  rejected:
    threshold: 5
